# Generated by Django 3.0.4 on 2020-03-19 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SentencePiece', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word',
            new_name='Tweet',
        ),
    ]
