# Generated by Django 3.0.4 on 2020-03-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SentencePiece', '0003_auto_20200320_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
