# Generated by Django 3.0.4 on 2020-03-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SentencePiece', '0004_auto_20200320_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='text',
            new_name='tweet',
        ),
    ]
